

module.exports = [
    'The River Boulevard',
    'The Cinnamon Angel',
    'The Mad Lounge',
    'The Bitter Stranger',
    'The Aqua Heart',
    'The Parlour',
    'Grace',
    'Mirrors',
    'Ivy',
    'The Hive',
    'The Cocoa Junction',
    'The Crystal Crown',
    'The Delhi Goddess',
    'The Champagne Parlour',
    'The Magical Deer',
    'The Maple',
    'Streetwise',
    'Elementary',
    'The Lotus',
    'The Grove',
    'The Oval Jewel',
    'The Royal Dairy',
    'The Hungry Fridge',
    'The Ruby Front',
    'The Royal Spices',
    'Trilogy',
    'Bandits',
    'The Smile',
    'The Nightingale',
    'Serenade',
    'The Eastern Moment',
    'The Sour Bass',
    'The Original Wok',
    'The Fable Nights',
    'The Savory Kitchen',
    'Lemon Grass',
    'Harmony',
    'Simmer Down',
    'Ivory',
    'Eureka',
    'The Autumn Ranch',
    'The Wild Fusion',
    'The Southern Moment',
    'The Island Spice',
    'The Light Pond',
    'The Lamb',
    'The Scarf',
    'Salutation',
    'Fabled',
    'Trinity',
    'The Coastal Spice',
    'The Whiskey Palace',
    'The River Rose',
    'The Western Fish',
    'The Narrow Shrimp',
    'Splash',
    'Twilight',
    'Lemon',
    'Twilight',
    'The Bell Tower',
    'The Pink Windmill',
    'The Big City Docks',
    'The Fiery Lighthouse',
    'The Streetwise Star',
    'The Boiling Goddess',
    'Potroast',
    'The Pearl',
    'The Boar',
    'Butlers',
    'Olive Grove',
    'The Cocoa Vine',
    'The Orange Tiger',
    'The Baking Scarf',
    'The Silver God',
    'The Cinnamon Well',
    'Rye',
    'Souls',
    'The Hog',
    'Chapter',
    'Streetwise',
    'The Fiery Garden',
    'The Silk Window',
    'The Incredible Chef',
    'The Honor Boulevard',
    'The Jade Duke',
    'Shazam',
    'Medallion',
    'Gentle',
    'The Boutique',
    'Embers',
    'The Vintage Chimney',
    'The Noodle Deer',
    'The Streetwise Garden',
    'The Rare Lantern',
    'The Crystal Blossom',
    'The Cave',
    'Petals',
    'Serenade',
    'Fiddler',
    'Tranquility'
]
